### ISSUE TITLE
Phases not saving with Update or project

### ISSUE THREAD

**Issue by BigActual** [realbig/RBM-Projects-Theme#3]
In this case it's when trying to Update the Jax Coll. project.

**Comment by d4mation** [comment]
This was caused by a conflict with Advanced Custom Fields and Project Panorama. Since the site was not using ACF on its own for anything, I just deactivated it and now it is fine.

Due to how Project Panorama is programmed though, since it sees that the ACF Repeater plugin exists, that one needs to stay active otherwise the Phase Repeaters do not work.

I'm going to open a couple issues for this in the Project Panorama repo.
